In [1]:
import pandas as pd

In [2]:
# read the data
path_to_spectral = '/data2/eranario/data/Multispectral-Potato/Signals/spectra.csv'
df_spectra = pd.read_csv(path_to_spectral, index_col=0)

In [3]:
df_spectra.head()

,Plant_ID,idstr,350,351,352,353,354,355,356,357,...,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500
PVY_Strain,,,,,,,,,,,,,,,,,,,,,
NTN,P61,61_mean,0.0753,0.0670,0.0631,0.0619,0.0640,0.0628,0.0608,0.0580,...,0.0372,0.0372,0.0371,0.0370,0.0372,0.0374,0.0372,0.0370,0.0370,0.0369
NO,P54,54_mean,0.0877,0.0871,0.0814,0.0778,0.0784,0.0747,0.0728,0.0744,...,0.0426,0.0425,0.0424,0.0423,0.0423,0.0423,0.0422,0.0421,0.0421,0.0422
NO,P56,56_mean,0.0780,0.0738,0.0769,0.0782,0.0758,0.0665,0.0602,0.0597,...,0.0337,0.0337,0.0336,0.0336,0.0335,0.0335,0.0335,0.0336,0.0334,0.0333
NO,P56,56_mean,0.0803,0.0787,0.0735,0.0684,0.0638,0.0594,0.0583,0.0621,...,0.0328,0.0325,0.0327,0.0328,0.0331,0.0334,0.0335,0.0336,0.0334,0.0332
NO,P56,56_mean,0.0735,0.0723,0.0697,0.0680,0.0677,0.0626,0.0589,0.0580,...,0.0340,0.0340,0.0338,0.0337,0.0338,0.0338,0.0338,0.0337,0.0337,0.0336

In [6]:
# remove first 2 columns
df_spectra_pruned = df_spectra[df_spectra.columns[2::]]

# remove row titles
df_spectra_pruned = df_spectra_pruned.reset_index(drop=True)
df_spectra_pruned.head()

,350,351,352,353,354,355,356,357,358,359,...,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500
0,0.0753,0.0670,0.0631,0.0619,0.0640,0.0628,0.0608,0.0580,0.0584,0.0585,...,0.0372,0.0372,0.0371,0.0370,0.0372,0.0374,0.0372,0.0370,0.0370,0.0369
1,0.0877,0.0871,0.0814,0.0778,0.0784,0.0747,0.0728,0.0744,0.0751,0.0729,...,0.0426,0.0425,0.0424,0.0423,0.0423,0.0423,0.0422,0.0421,0.0421,0.0422
2,0.0780,0.0738,0.0769,0.0782,0.0758,0.0665,0.0602,0.0597,0.0629,0.0655,...,0.0337,0.0337,0.0336,0.0336,0.0335,0.0335,0.0335,0.0336,0.0334,0.0333
3,0.0803,0.0787,0.0735,0.0684,0.0638,0.0594,0.0583,0.0621,0.0631,0.0648,...,0.0328,0.0325,0.0327,0.0328,0.0331,0.0334,0.0335,0.0336,0.0334,0.0332
4,0.0735,0.0723,0.0697,0.0680,0.0677,0.0626,0.0589,0.0580,0.0579,0.0584,...,0.0340,0.0340,0.0338,0.0337,0.0338,0.0338,0.0338,0.0337,0.0337,0.0336

In [7]:
# check number of columns and rows
print('Number of columns: ', len(df_spectra_pruned.columns))
print('Number of rows: ', len(df_spectra_pruned))

Number of columns:  2151
Number of rows:  474